// Code generated by "stringer -type=IFDtag"; DO NOT EDIT.

package arw

import "fmt"

const _IFDtag_name = "NewSubFileTypeCompressionImageDescriptionMakeModelOrientationXResolutionYResolutionResolutionUnitSoftwareDateTimeSubIFDsJPEGInterchangeFormatJPEGInterchangeFormatLengthYCbCrPositioningExifTagGPSTagInteroperabilityTagPrintImageMatchingDNGPrivateData"

var _IFDtag_map = map[IFDtag]string{
	254:   _IFDtag_name[0:14],
	259:   _IFDtag_name[14:25],
	270:   _IFDtag_name[25:41],
	271:   _IFDtag_name[41:45],
	272:   _IFDtag_name[45:50],
	274:   _IFDtag_name[50:61],
	282:   _IFDtag_name[61:72],
	283:   _IFDtag_name[72:83],
	296:   _IFDtag_name[83:97],
	305:   _IFDtag_name[97:105],
	306:   _IFDtag_name[105:113],
	330:   _IFDtag_name[113:120],
	513:   _IFDtag_name[120:141],
	514:   _IFDtag_name[141:168],
	531:   _IFDtag_name[168:184],
	34665: _IFDtag_name[184:191],
	34853: _IFDtag_name[191:197],
	40965: _IFDtag_name[197:216],
	50341: _IFDtag_name[216:234],
	50740: _IFDtag_name[234:248],
}

func (i IFDtag) String() string {
	if str, ok := _IFDtag_map[i]; ok {
		return str
	}
	return fmt.Sprintf("IFDtag(%d)", i)
}
